const riddleslist = [
  { riddle: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", answer: "Echo" },
  { riddle: "The more of me you take, the more you leave behind. What am I?", answer: "Footsteps" },
  { riddle: "What can run but never walks, has a bed but never sleeps, has a mouth but never talks?", answer: "River" },
  { riddle: "I’m tall when I’m young, and I’m short when I’m old. What am I?", answer: "Candle" },
  { riddle: "What can fill a room but takes up no space?", answer: "Light" },
  { riddle: "What goes up but never comes down?", answer: "Age" },
  { riddle: "What gets wetter the more it dries?", answer: "Towel" },
  { riddle: "What has many keys but can’t open a single lock?", answer: "Piano" },
  { riddle: "What has hands but can’t clap?", answer: "Clock" },
  { riddle: "What has to be broken before you can use it?", answer: "Egg" },
  { riddle: "What has one eye but can’t see?", answer: "Needle" },
  { riddle: "What is always in front of you but can’t be seen?", answer: "Future" },
  { riddle: "What goes through cities and fields but never moves?", answer: "Road" },
  { riddle: "What has a head, a tail, but no body?", answer: "Coin" },
  { riddle: "I have branches, but no fruit, trunk or leaves. What am I?", answer: "Bank" },
  { riddle: "You see me once in June, twice in November, but not at all in May. What am I?", answer: "The letter E" },
  { riddle: "What disappears as soon as you say its name?", answer: "Silence" },
  { riddle: "What invention lets you look right through a wall?", answer: "Window" },
  { riddle: "I shave every day, but my beard stays the same. What am I?", answer: "Barber" },
  { riddle: "The more you take, the bigger I get. What am I?", answer: "Hole" },
  { riddle: "What has a neck but no head?", answer: "Bottle" },
  { riddle: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "The letter M" },
  { riddle: "I have keys but no locks. I have space but no room. You can enter but you can’t go outside. What am I?", answer: "Keyboard" },
  { riddle: "What can’t be put in a saucepan?", answer: "Its lid" },
  { riddle: "I’m not alive, but I grow. I don’t have lungs, but I need air. What am I?", answer: "Fire" },
  { riddle: "If two’s company, and three’s a crowd, what are four and five?", answer: "Nine" },
  { riddle: "What has legs but doesn’t walk?", answer: "Table" },
  { riddle: "What comes down but never goes up?", answer: "Rain" },
  { riddle: "What has cities, but no houses; forests, but no trees; and rivers, but no water?", answer: "Map" },
  { riddle: "I’m found in socks, scarves and mittens. What am I?", answer: "Yarn" },
  { riddle: "What begins with T, ends with T, and has T in it?", answer: "Teapot" },
  { riddle: "I’m light as a feather, yet the strongest man can’t hold me for more than 5 minutes. What am I?", answer: "Breath" },
  { riddle: "What five-letter word becomes shorter when you add two letters to it?", answer: "Short" },
  { riddle: "What has a bottom at the top?", answer: "Legs" },
  { riddle: "If you drop me, I’m sure to crack, but give me a smile and I’ll always smile back. What am I?", answer: "Mirror" },
  { riddle: "What comes at the end of everything?", answer: "The letter G" },
  { riddle: "Which word is spelled incorrectly in every dictionary?", answer: "Incorrectly" },
  { riddle: "What can travel around the world while staying in the same corner?", answer: "Stamp" },
  { riddle: "What has four wheels and flies?", answer: "Garbage truck" },
  { riddle: "What has one head, one foot, and four legs?", answer: "Bed" },
  { riddle: "I fly without wings. I cry without eyes. Wherever I go, darkness flies. What am I?", answer: "Cloud" },
  { riddle: "What word is spelled the same forwards, backwards and upside down?", answer: "NOON" },
  { riddle: "What kind of coat can only be put on when wet?", answer: "Paint" },
  { riddle: "If you have me, you want to share me. If you share me, you don’t have me. What am I?", answer: "Secret" },
  { riddle: "I go all around the world but always stay in a corner. What am I?", answer: "Stamp" },
  { riddle: "What is full of holes but still holds water?", answer: "Sponge" },
  { riddle: "The more you take away, the more I become. What am I?", answer: "Hole" },
  { riddle: "What has a ring but no finger?", answer: "Phone" },
  { riddle: "What comes once in a year, twice in a week, but never in a day?", answer: "The letter E" },
  { riddle: "A man rode into town on Tuesday and left two days later on Tuesday. How?", answer: "His horse's name was Tuesday" },
  { riddle: "What belongs to you but others use it more than you do?", answer: "Your name" },
  { riddle: "What can't talk but will reply when spoken to?", answer: "Echo" },
  { riddle: "What can be broken but never held?", answer: "Promise" },
  { riddle: "What gets bigger the more you take away from it?", answer: "Hole" },
  { riddle: "The more you have of me, the less you see. What am I?", answer: "Darkness" },
  { riddle: "What can’t be used until it’s broken?", answer: "Egg" },
  { riddle: "What is seen in the middle of March and April that can't be seen at the beginning or end?", answer: "The letter R" },
  { riddle: "What English word has three consecutive double letters?", answer: "Bookkeeper" },
  { riddle: "What starts with a P, ends with an E, and has thousands of letters?", answer: "Post Office" },
  { riddle: "What is always in front of you but can’t be seen?", answer: "Future" },
  { riddle: "What begins with an E but only contains one letter?", answer: "Envelope" },
  { riddle: "Forward I am heavy, but backward I’m not. What am I?", answer: "Ton" },
  { riddle: "What has 13 hearts, but no other organs?", answer: "Deck of cards" },
  { riddle: "What comes in a minute, twice in a moment, but never in a thousand years?", answer: "M" },
  { riddle: "What 4-letter word can be written forward, backward or upside down, and still be read from left to right?", answer: "NOON" },
  { riddle: "What room do ghosts avoid?", answer: "Living room" },
  { riddle: "What type of music do mummies listen to?", answer: "Wrap" },
  { riddle: "What has 4 eyes but can’t see?", answer: "Mississippi" },
  { riddle: "What do you throw out when you want to use it, and take in when you don’t want to use it?", answer: "Anchor" },
  { riddle: "What word contains all 26 letters?", answer: "Alphabet" },
  { riddle: "What kind of tree can you carry in your hand?", answer: "Palm" },
  { riddle: "What begins with an 'e' and only contains one letter?", answer: "Envelope" },
  { riddle: "What has no beginning, end, or middle?", answer: "Doughnut" },
  { riddle: "What comes once in a second, once in a minute, and twice in a millennium?", answer: "N" },
  { riddle: "If you throw a red stone into the blue sea, what will it become?", answer: "Wet" },
  { riddle: "I have a heart that doesn’t beat. What am I?", answer: "Artichoke" },
  { riddle: "What begins and ends with an E but only has one letter?", answer: "Envelope" },
  { riddle: "What has a face and two hands but no arms or legs?", answer: "Clock" },
  { riddle: "I go up but never down. What am I?", answer: "Age" },
  { riddle: "What can be cracked, made, told, and played?", answer: "Joke" },
  { riddle: "What has ears but cannot hear?", answer: "Corn" },
  { riddle: "You answer me, although I never ask you questions. What am I?", answer: "Phone" },
  { riddle: "What can’t be seen but can be heard and will not speak unless spoken to?", answer: "Echo" },
  { riddle: "If you have one, you want to share it. Once you share it, you do not have it. What is it?", answer: "Secret" },
  { riddle: "What gets sharper the more you use it?", answer: "Brain" },
  { riddle: "What can't be burned in a fire nor drowned in water?", answer: "Ice" },
  { riddle: "I am taken from a mine, and shut in a wooden case. Used by students every day. What am I?", answer: "Pencil lead" },
  { riddle: "You see a boat filled with people, yet there isn’t a single person on board. How?", answer: "They’re all married" },
  { riddle: "What is black when it’s clean and white when it’s dirty?", answer: "Blackboard" },
  { riddle: "I’m not a bird, but I can fly through the sky. I’m not a river, but I’m full of water. What am I?", answer: "Cloud" }
];