const riddleslist = [
  { riddle: "What comes next in the sequence: 2, 4, 8, 16, ?", answer: "32" },
  { riddle: "What is half of a quarter of 100?", answer: "12.5" },
  { riddle: "I am a number. Multiply me by 2, add 10, divide by 4 and subtract 3. You get 5. What number am I?", answer: "6" },
  { riddle: "A man has 4 daughters, and each has a brother. How many children does he have?", answer: "5" },
  { riddle: "What two numbers multiply to 36 and add up to 13?", answer: "9 and 4" },
  { riddle: "What is the next prime number after 29?", answer: "31" },
  { riddle: "What 3-digit number reads the same upside down?", answer: "181" },
  { riddle: "I am a two-digit number. My tens digit is double my ones digit and the sum of both digits is 12. What number am I?", answer: "84" },
  { riddle: "A bat and a ball cost $1.10. The bat costs $1 more than the ball. How much does the ball cost?", answer: "0.05" },
  { riddle: "What is 7 times 6?", answer: "42" },
  { riddle: "If 3 pencils cost $1.50, how much does 1 pencil cost?", answer: "0.50" },
  { riddle: "How many degrees in a triangle?", answer: "180" },
  { riddle: "What is the square root of 144?", answer: "12" },
  { riddle: "If 5 machines make 5 widgets in 5 minutes, how long for 100 machines to make 100 widgets?", answer: "5" },
  { riddle: "Which number is missing: 3, 6, 9, __, 15?", answer: "12" },
  { riddle: "What number do you get if you multiply all of the numbers on a phone keypad?", answer: "0" },
  { riddle: "What is 10% of 250?", answer: "25" },
  { riddle: "Divide 30 by half and add 10. What do you get?", answer: "70" },
  { riddle: "What is 2 cubed?", answer: "8" },
  { riddle: "What’s the next number: 1, 4, 9, 16, ?", answer: "25" },
  { riddle: "What’s the next number: 1, 1, 2, 3, 5, 8, ?", answer: "13" },
  { riddle: "What’s 15% of 200?", answer: "30" },
  { riddle: "What is the value of π (pi) to two decimal places?", answer: "3.14" },
  { riddle: "How many sides does a decagon have?", answer: "10" },
  { riddle: "If you have 3 apples and take away 2, how many do you have?", answer: "2" },
  { riddle: "What is 3 squared plus 4 squared?", answer: "25" },
  { riddle: "How many zeros are there in one thousand?", answer: "3" },
  { riddle: "If a dozen eggs cost $1.20, how much does one egg cost?", answer: "0.10" },
  { riddle: "What is 25 x 4?", answer: "100" },
  { riddle: "Which is greater: ⅓ or 0.3?", answer: "⅓" },
  { riddle: "What is 100 divided by 4, then multiplied by 2?", answer: "50" },
  { riddle: "A farmer has 17 sheep. All but 9 run away. How many are left?", answer: "9" },
  { riddle: "If a car travels 60 miles in 1 hour, how far in 2.5 hours?", answer: "150" },
  { riddle: "What number is the Roman numeral L?", answer: "50" },
  { riddle: "What is the product of 7 and 9?", answer: "63" },
  { riddle: "Which number has no factors except 1 and itself and comes after 11?", answer: "13" },
  { riddle: "What is 1/4 of 80?", answer: "20" },
  { riddle: "What is 12% of 50?", answer: "6" },
  { riddle: "How many minutes in 2 hours?", answer: "120" },
  { riddle: "What is 6 factorial (6!)?", answer: "720" },
  { riddle: "Which is larger: 0.5 or 1/3?", answer: "0.5" },
  { riddle: "What’s the square root of 225?", answer: "15" },
  { riddle: "A rectangle is 4cm by 6cm. What's its area?", answer: "24" },
  { riddle: "What number is twice the sum of its digits?", answer: "18" },
  { riddle: "How many days in 4 weeks?", answer: "28" },
  { riddle: "If you triple 6 and subtract 3, what do you get?", answer: "15" },
  { riddle: "What is 90% of 60?", answer: "54" },
  { riddle: "What is ⅕ of 100?", answer: "20" },
  { riddle: "What’s ⅓ of 60?", answer: "20" },
  { riddle: "What is 1/8 of 64?", answer: "8" },
  { riddle: "How many even numbers between 1 and 10?", answer: "4" },
  { riddle: "What’s the difference between 100 and 37?", answer: "63" },
  { riddle: "How many sides does a hexagon have?", answer: "6" },
  { riddle: "What is the sum of the angles in a square?", answer: "360" },
  { riddle: "What is 2 to the power of 5?", answer: "32" },
  { riddle: "What number comes before 1,000,000?", answer: "999999" },
  { riddle: "What is 5 + 5 x 2?", answer: "15" },
  { riddle: "If it’s 3PM now, what time will it be in 100 hours?", answer: "7AM" },
  { riddle: "What’s 25% of 300?", answer: "75" },
  { riddle: "If you cut a pie into 6 equal slices and eat 2, what fraction is left?", answer: "2/3" },
  { riddle: "What number multiplied by 3 equals 81?", answer: "27" },
  { riddle: "Which number is a square and a cube?", answer: "64" },
  { riddle: "How many centimeters in a meter?", answer: "100" },
  { riddle: "What number is missing: 10, 20, __, 40?", answer: "30" },
  { riddle: "What is 15 + 18?", answer: "33" },
  { riddle: "What is the perimeter of a square with side 5?", answer: "20" },
  { riddle: "What’s 9 x 11?", answer: "99" },
  { riddle: "What is 2.5 + 2.5?", answer: "5" },
  { riddle: "If you subtract 15 from 45, what do you get?", answer: "30" },
  { riddle: "What number is one-fifth of 100?", answer: "20" },
  { riddle: "If 10 cookies are split among 5 friends, how many each?", answer: "2" },
  { riddle: "What’s 0.1 x 10?", answer: "1" },
  { riddle: "What is 20% of 400?", answer: "80" },
  { riddle: "What is the average of 2, 4, and 6?", answer: "4" },
  { riddle: "What is 7 squared?", answer: "49" },
  { riddle: "If you add 5 to me, I become 10. What am I?", answer: "5" },
  { riddle: "How many quarters in $5?", answer: "20" },
  { riddle: "If a triangle has angles 90° and 45°, what’s the third?", answer: "45" },
  { riddle: "How many odd numbers between 1 and 10?", answer: "5" },
  { riddle: "What is 100 divided by 10?", answer: "10" },
  { riddle: "What’s the next even number after 98?", answer: "100" },
  { riddle: "What is 3 x 12?", answer: "36" },
  { riddle: "If you earn $15 per hour and work 6 hours, how much?", answer: "90" },
  { riddle: "What’s the difference between 81 and 64?", answer: "17" },
  { riddle: "What number is both a cube and square between 1 and 100?", answer: "64" },
  { riddle: "If 3x = 12, what is x?", answer: "4" },
  { riddle: "What’s 45 divided by 5?", answer: "9" },
  { riddle: "If a book costs $12 and you pay $20, how much change?", answer: "8" },
  { riddle: "What’s 18 more than 64?", answer: "82" },
  { riddle: "What is the product of 11 and 11?", answer: "121" },
  { riddle: "If you double a number and subtract 4, you get 10. What is the number?", answer: "7" }
];